apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kafka-to-influxdb-xlbt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kafka-to-influxdb-xlbt
    app.kubernetes.io/part-of: kafka-to-influxdb
  name: kafka-to-influxdb-xlbt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kafka-to-influxdb-xlbt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kafka-to-influxdb-xlbt
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rshah-tenant/kafka-to-influxdb/kafka-to-influxdb-xlbt@sha256:b88d38fc715ecbcaa52686ec0d45e6fa53c388fc787d73acba10341a208ac03b
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
status: {}
